export interface CriminalArticle {
  id: string
  article: string
  description: string
  fine: number
  penalty: number
  bail: number
}

export const criminalArticles: CriminalArticle[] = [
  // CRIMES CONTRA A VIDA
  {
    id: "art-1-1",
    article: "Art. 1.1",
    description: "Lesão corporal leve",
    penalty: 10,
    fine: 1000,
    bail: 500,
  },
  {
    id: "art-1-2",
    article: "Art. 1.2",
    description: "Lesão corporal grave",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-1-3",
    article: "Art. 1.3",
    description: "Omissão de socorro",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-1-4",
    article: "Art. 1.4",
    description: "Maus tratos",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-1-5",
    article: "Art. 1.5",
    description: "Abandono de incapaz",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-1-6",
    article: "Art. 1.6",
    description: "Homicídio culposo",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-1-7",
    article: "Art. 1.7",
    description: "Homicídio doloso",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-1-8",
    article: "Art. 1.8",
    description: "Latrocínio",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },

  // CRIMES CONTRA A HONRA E A DIGNIDADE
  {
    id: "art-2-1",
    article: "Art. 2.1",
    description: "Atentado ao pudor",
    penalty: 50,
    fine: 50000,
    bail: -1,
  },
  {
    id: "art-2-2",
    article: "Art. 2.2",
    description: "Calúnia",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-2-3",
    article: "Art. 2.3",
    description: "Difamação",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-2-4",
    article: "Art. 2.4",
    description: "Injúria",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-2-5",
    article: "Art. 2.5",
    description: "Assédio",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-2-6",
    article: "Art. 2.6",
    description: "Ameaça",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-2-7",
    article: "Art. 2.7",
    description: "Uso indevido da imagem",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },

  // CRIMES CONTRA O PATRIMÔNIO
  {
    id: "art-3-1",
    article: "Art. 3.1",
    description: "Direitos autorais",
    penalty: 10,
    fine: 1000,
    bail: 500,
  },
  {
    id: "art-3-2",
    article: "Art. 3.2",
    description: "Furto",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-3-3",
    article: "Art. 3.3",
    description: "Roubo",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-3-4",
    article: "Art. 3.4",
    description: "Extorsão",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-3-5",
    article: "Art. 3.5",
    description: "Destruição do patrimônio privado",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-3-6",
    article: "Art. 3.6",
    description: "Destruição do patrimônio público",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-3-7",
    article: "Art. 3.7",
    description: "Invasão à propriedade",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },

  // CRIMES CONTRA A ORDEM PÚBLICA
  {
    id: "art-4-1",
    article: "Art. 4.1",
    description: "Incitar a prática de crime",
    penalty: 10,
    fine: 1000,
    bail: 500,
  },
  {
    id: "art-4-2",
    article: "Art. 4.2",
    description: "Associação criminosa",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-3",
    article: "Art. 4.3",
    description: "Formação de quadrilha",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-4",
    article: "Art. 4.4",
    description: "Posse de drogas (até 10 unidades)",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-5",
    article: "Art. 4.5",
    description: "Tráfico de drogas (acima de 10 unidades)",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-6",
    article: "Art. 4.6",
    description: "Posse ilegal de munições (até 50 unidades)",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-7",
    article: "Art. 4.7",
    description: "Porte ilegal de armas (até 2 unidades)",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-8",
    article: "Art. 4.8",
    description: "Tráfico de armas (acima de 2 unidades)",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-9",
    article: "Art. 4.9",
    description: "Tráfico de munições (acima de 50 unidades)",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-10",
    article: "Art. 4.10",
    description: "Posse de dinheiro sujo",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-11",
    article: "Art. 4.11",
    description: "Posse de materiais ilegais",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-12",
    article: "Art. 4.12",
    description: "Ocultação facial",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-13",
    article: "Art. 4.13",
    description: "Posse de equipamento militar ou restrito",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-14",
    article: "Art. 4.14",
    description: "Posse de explosivos",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-15",
    article: "Art. 4.15",
    description: "Uso indevido de armamento",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-16",
    article: "Art. 4.16",
    description: "Evasão",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-17",
    article: "Art. 4.17",
    description: "Perturbação da ordem pública",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-4-18",
    article: "Art. 4.18",
    description: "Lavagem de dinheiro",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },

  // CRIMES CONTRA A ADMINISTRAÇÃO PÚBLICA
  {
    id: "art-5-1",
    article: "Art. 5.1",
    description: "Falsidade ideológica",
    penalty: 10,
    fine: 1000,
    bail: 500,
  },
  {
    id: "art-5-2",
    article: "Art. 5.2",
    description: "Exercício ilegal da profissão",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-3",
    article: "Art. 5.3",
    description: "Abandono de função",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-4",
    article: "Art. 5.4",
    description: "Desobediência",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-5",
    article: "Art. 5.5",
    description: "Desacato",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-6",
    article: "Art. 5.6",
    description: "Corrupção passiva",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-7",
    article: "Art. 5.7",
    description: "Suborno",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-8",
    article: "Art. 5.8",
    description: "Fraude",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-9",
    article: "Art. 5.9",
    description: "Prevaricação",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-10",
    article: "Art. 5.10",
    description: "Abuso de autoridade",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-11",
    article: "Art. 5.11",
    description: "Falso testemunho",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
  {
    id: "art-5-12",
    article: "Art. 5.12",
    description: "Denunciação caluniosa",
    penalty: 15,
    fine: 2000,
    bail: 1000,
  },
]

export const categories = {
  "Crimes contra a Vida": ["art-1-1", "art-1-2", "art-1-3", "art-1-4", "art-1-5", "art-1-6", "art-1-7", "art-1-8"],
  "Crimes contra a Honra e Dignidade": ["art-2-1", "art-2-2", "art-2-3", "art-2-4", "art-2-5", "art-2-6", "art-2-7"],
  "Crimes contra o Patrimônio": ["art-3-1", "art-3-2", "art-3-3", "art-3-4", "art-3-5", "art-3-6", "art-3-7"],
  "Crimes contra a Ordem Pública": [
    "art-4-1",
    "art-4-2",
    "art-4-3",
    "art-4-4",
    "art-4-5",
    "art-4-6",
    "art-4-7",
    "art-4-8",
    "art-4-9",
    "art-4-10",
    "art-4-11",
    "art-4-12",
    "art-4-13",
    "art-4-14",
    "art-4-15",
    "art-4-16",
    "art-4-17",
    "art-4-18",
  ],
  "Crimes contra a Administração Pública": [
    "art-5-1",
    "art-5-2",
    "art-5-3",
    "art-5-4",
    "art-5-5",
    "art-5-6",
    "art-5-7",
    "art-5-8",
    "art-5-9",
    "art-5-10",
    "art-5-11",
    "art-5-12",
  ],
}
